use_frameworks!

platform :ios, '8.0'

target 'pod_test_Example' do
  pod 'pod_test', :path => '../'
  #pod 'day02', :git =>'https://github.com/macjaz/day02.git'
  
  
  target 'pod_test_Tests' do
    inherit! :search_paths

    
  end
end
