// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/taikang/im/protobuf/BroadcastMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#import <SakuraKit/BroadcastMessage.pbobjc.h>
#import <SakuraKit/MessageBody.pbobjc.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#import "BroadcastMessage.pbobjc.h"
#import "MessageBody.pbobjc.h"
#endif


// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - BroadcastMessageRoot

@implementation BroadcastMessageRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - BroadcastMessageRoot_FileDescriptor

static GPBFileDescriptor *BroadcastMessageRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - BroadcastMessage

@implementation BroadcastMessage

@dynamic messageId;
@dynamic channelId;
@dynamic channelLabel;
@dynamic from;
@dynamic sourceLabel;
@dynamic to;
@dynamic deviceType;
@dynamic domain;
@dynamic hasBody, body;

typedef struct BroadcastMessage__storage_ {
  uint32_t _has_storage_[1];
  int32_t deviceType;
  NSString *messageId;
  NSString *channelId;
  NSString *channelLabel;
  NSString *from;
  NSString *sourceLabel;
  NSString *to;
  NSString *domain;
  MessageBody *body;
} BroadcastMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "messageId",
        .dataTypeSpecific.className = NULL,
        .number = BroadcastMessage_FieldNumber_MessageId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BroadcastMessage__storage_, messageId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "channelId",
        .dataTypeSpecific.className = NULL,
        .number = BroadcastMessage_FieldNumber_ChannelId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(BroadcastMessage__storage_, channelId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "channelLabel",
        .dataTypeSpecific.className = NULL,
        .number = BroadcastMessage_FieldNumber_ChannelLabel,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(BroadcastMessage__storage_, channelLabel),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "from",
        .dataTypeSpecific.className = NULL,
        .number = BroadcastMessage_FieldNumber_From,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(BroadcastMessage__storage_, from),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sourceLabel",
        .dataTypeSpecific.className = NULL,
        .number = BroadcastMessage_FieldNumber_SourceLabel,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(BroadcastMessage__storage_, sourceLabel),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "to",
        .dataTypeSpecific.className = NULL,
        .number = BroadcastMessage_FieldNumber_To,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(BroadcastMessage__storage_, to),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceType",
        .dataTypeSpecific.className = NULL,
        .number = BroadcastMessage_FieldNumber_DeviceType,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(BroadcastMessage__storage_, deviceType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "domain",
        .dataTypeSpecific.className = NULL,
        .number = BroadcastMessage_FieldNumber_Domain,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(BroadcastMessage__storage_, domain),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "body",
        .dataTypeSpecific.className = GPBStringifySymbol(MessageBody),
        .number = BroadcastMessage_FieldNumber_Body,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(BroadcastMessage__storage_, body),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BroadcastMessage class]
                                     rootClass:[BroadcastMessageRoot class]
                                          file:BroadcastMessageRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BroadcastMessage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\005\001\t\000\002\t\000\003\014\000\005\013\000\007\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
