// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/taikang/im/protobuf/ChatMessageNotifyAck.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#import <SakuraKit/ChatMessageNotifyAck.pbobjc.h>

#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#import "ChatMessageNotifyAck.pbobjc.h"
#import "GPBProtocolBuffers_RuntimeSupport.h"


#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ChatMessageNotifyAckRoot

@implementation ChatMessageNotifyAckRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - ChatMessageNotifyAckRoot_FileDescriptor

static GPBFileDescriptor *ChatMessageNotifyAckRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - ChatMessageNotifyAck

@implementation ChatMessageNotifyAck

@dynamic messageId;
@dynamic from;
@dynamic deviceType;
@dynamic to;

typedef struct ChatMessageNotifyAck__storage_ {
  uint32_t _has_storage_[1];
  int32_t deviceType;
  NSString *messageId;
  NSString *from;
  NSString *to;
} ChatMessageNotifyAck__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "messageId",
        .dataTypeSpecific.className = NULL,
        .number = ChatMessageNotifyAck_FieldNumber_MessageId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ChatMessageNotifyAck__storage_, messageId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "from",
        .dataTypeSpecific.className = NULL,
        .number = ChatMessageNotifyAck_FieldNumber_From,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ChatMessageNotifyAck__storage_, from),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceType",
        .dataTypeSpecific.className = NULL,
        .number = ChatMessageNotifyAck_FieldNumber_DeviceType,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ChatMessageNotifyAck__storage_, deviceType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "to",
        .dataTypeSpecific.className = NULL,
        .number = ChatMessageNotifyAck_FieldNumber_To,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ChatMessageNotifyAck__storage_, to),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ChatMessageNotifyAck class]
                                     rootClass:[ChatMessageNotifyAckRoot class]
                                          file:ChatMessageNotifyAckRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ChatMessageNotifyAck__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\t\000\003\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
