// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/taikang/im/protobuf/CustomerMessageReqNotify.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MessageBody;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CustomerMessageReqNotifyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface CustomerMessageReqNotifyRoot : GPBRootObject
@end

#pragma mark - CustomerMessageReqNotify

typedef GPB_ENUM(CustomerMessageReqNotify_FieldNumber) {
  CustomerMessageReqNotify_FieldNumber_MessageId = 1,
  CustomerMessageReqNotify_FieldNumber_SessionId = 2,
  CustomerMessageReqNotify_FieldNumber_SessionLabel = 3,
  CustomerMessageReqNotify_FieldNumber_From = 4,
  CustomerMessageReqNotify_FieldNumber_FromLabel = 5,
  CustomerMessageReqNotify_FieldNumber_To = 6,
  CustomerMessageReqNotify_FieldNumber_ToLabel = 7,
  CustomerMessageReqNotify_FieldNumber_DeviceType = 8,
  CustomerMessageReqNotify_FieldNumber_Body = 9,
  CustomerMessageReqNotify_FieldNumber_Domain = 10,
  CustomerMessageReqNotify_FieldNumber_SessionType = 11,
};

@interface CustomerMessageReqNotify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionLabel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *from;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fromLabel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *to;

@property(nonatomic, readwrite, copy, null_resettable) NSString *toLabel;

@property(nonatomic, readwrite) int32_t deviceType;

@property(nonatomic, readwrite, strong, null_resettable) MessageBody *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@property(nonatomic, readwrite, copy, null_resettable) NSString *domain;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionType;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
