// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/taikang/im/protobuf/DisconnectNotify.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DisconnectNotifyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DisconnectNotifyRoot : GPBRootObject
@end

#pragma mark - DisconnectNotify

typedef GPB_ENUM(DisconnectNotify_FieldNumber) {
  DisconnectNotify_FieldNumber_Token = 1,
  DisconnectNotify_FieldNumber_Identify = 2,
  DisconnectNotify_FieldNumber_DeviceType = 3,
  DisconnectNotify_FieldNumber_ProtoType = 4,
  DisconnectNotify_FieldNumber_Reason = 5,
  DisconnectNotify_FieldNumber_ConnectionId = 6,
};

@interface DisconnectNotify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, copy, null_resettable) NSString *identify;

@property(nonatomic, readwrite) int32_t deviceType;

@property(nonatomic, readwrite) int32_t protoType;

/** 0 unknown, 1 force disconnect by admin, 2 force disconnect by another device, 3 disconnect by user */
@property(nonatomic, readwrite) int32_t reason;

@property(nonatomic, readwrite, copy, null_resettable) NSString *connectionId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
