// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/taikang/im/protobuf/GroupMessageNotify.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#import <SakuraKit/GroupMessageNotify.pbobjc.h>
#import <SakuraKit/MessageBody.pbobjc.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#import "GroupMessageNotify.pbobjc.h"
#import "MessageBody.pbobjc.h"
#endif


// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GroupMessageNotifyRoot

@implementation GroupMessageNotifyRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - GroupMessageNotifyRoot_FileDescriptor

static GPBFileDescriptor *GroupMessageNotifyRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GroupMessageNotify

@implementation GroupMessageNotify

@dynamic messageId;
@dynamic from;
@dynamic to;
@dynamic groupId;
@dynamic deviceType;
@dynamic hasBody, body;
@dynamic sourceLabel;
@dynamic targetLabel;
@dynamic domain;

typedef struct GroupMessageNotify__storage_ {
  uint32_t _has_storage_[1];
  int32_t deviceType;
  NSString *messageId;
  NSString *from;
  NSString *to;
  NSString *groupId;
  MessageBody *body;
  NSString *sourceLabel;
  NSString *targetLabel;
  NSString *domain;
} GroupMessageNotify__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "messageId",
        .dataTypeSpecific.className = NULL,
        .number = GroupMessageNotify_FieldNumber_MessageId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GroupMessageNotify__storage_, messageId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "from",
        .dataTypeSpecific.className = NULL,
        .number = GroupMessageNotify_FieldNumber_From,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GroupMessageNotify__storage_, from),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "to",
        .dataTypeSpecific.className = NULL,
        .number = GroupMessageNotify_FieldNumber_To,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GroupMessageNotify__storage_, to),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "groupId",
        .dataTypeSpecific.className = NULL,
        .number = GroupMessageNotify_FieldNumber_GroupId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GroupMessageNotify__storage_, groupId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceType",
        .dataTypeSpecific.className = NULL,
        .number = GroupMessageNotify_FieldNumber_DeviceType,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GroupMessageNotify__storage_, deviceType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "body",
        .dataTypeSpecific.className = GPBStringifySymbol(MessageBody),
        .number = GroupMessageNotify_FieldNumber_Body,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(GroupMessageNotify__storage_, body),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "sourceLabel",
        .dataTypeSpecific.className = NULL,
        .number = GroupMessageNotify_FieldNumber_SourceLabel,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(GroupMessageNotify__storage_, sourceLabel),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "targetLabel",
        .dataTypeSpecific.className = NULL,
        .number = GroupMessageNotify_FieldNumber_TargetLabel,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(GroupMessageNotify__storage_, targetLabel),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "domain",
        .dataTypeSpecific.className = NULL,
        .number = GroupMessageNotify_FieldNumber_Domain,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(GroupMessageNotify__storage_, domain),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GroupMessageNotify class]
                                     rootClass:[GroupMessageNotifyRoot class]
                                          file:GroupMessageNotifyRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GroupMessageNotify__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\005\001\t\000\004\007\000\005\n\000\007\013\000\010\013\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
