// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/taikang/im/protobuf/message/MessageBody.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class CustomMessage;
@class FileMessage;
@class ImageMessage;
@class NewsMessage;
@class RecallMessage;
@class RemindMessage;
@class ShortVideoMessage;
@class SystemMessage;
@class TextMessage;
@class VideoMessage;
@class VoiceMessage;
GPB_ENUM_FWD_DECLARE(MessageType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MessageBodyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MessageBodyRoot : GPBRootObject
@end

#pragma mark - MessageBody

typedef GPB_ENUM(MessageBody_FieldNumber) {
  MessageBody_FieldNumber_MessageType = 1,
  MessageBody_FieldNumber_TextMessage = 2,
  MessageBody_FieldNumber_ImageMessage = 3,
  MessageBody_FieldNumber_VoiceMessage = 4,
  MessageBody_FieldNumber_VideoMessage = 5,
  MessageBody_FieldNumber_ShortVideoMessage = 6,
  MessageBody_FieldNumber_NewsMessage = 7,
  MessageBody_FieldNumber_FileMessage = 8,
  MessageBody_FieldNumber_CustomMessage = 9,
  MessageBody_FieldNumber_SystemMessage = 10,
  MessageBody_FieldNumber_RecallMessage = 11,
  MessageBody_FieldNumber_Extra = 12,
  MessageBody_FieldNumber_NotifyPassThrough = 13,
  MessageBody_FieldNumber_RemindMessage = 14,
  MessageBody_FieldNumber_RequestEvent = 15,
};

@interface MessageBody : GPBMessage

@property(nonatomic, readwrite) enum MessageType messageType;

@property(nonatomic, readwrite, strong, null_resettable) TextMessage *textMessage;
/** Test to see if @c textMessage has been set. */
@property(nonatomic, readwrite) BOOL hasTextMessage;

@property(nonatomic, readwrite, strong, null_resettable) ImageMessage *imageMessage;
/** Test to see if @c imageMessage has been set. */
@property(nonatomic, readwrite) BOOL hasImageMessage;

@property(nonatomic, readwrite, strong, null_resettable) VoiceMessage *voiceMessage;
/** Test to see if @c voiceMessage has been set. */
@property(nonatomic, readwrite) BOOL hasVoiceMessage;

@property(nonatomic, readwrite, strong, null_resettable) VideoMessage *videoMessage;
/** Test to see if @c videoMessage has been set. */
@property(nonatomic, readwrite) BOOL hasVideoMessage;

@property(nonatomic, readwrite, strong, null_resettable) ShortVideoMessage *shortVideoMessage;
/** Test to see if @c shortVideoMessage has been set. */
@property(nonatomic, readwrite) BOOL hasShortVideoMessage;

@property(nonatomic, readwrite, strong, null_resettable) NewsMessage *newsMessage;
/** Test to see if @c newsMessage has been set. */
@property(nonatomic, readwrite) BOOL hasNewsMessage;

@property(nonatomic, readwrite, strong, null_resettable) FileMessage *fileMessage;
/** Test to see if @c fileMessage has been set. */
@property(nonatomic, readwrite) BOOL hasFileMessage;

@property(nonatomic, readwrite, strong, null_resettable) CustomMessage *customMessage;
/** Test to see if @c customMessage has been set. */
@property(nonatomic, readwrite) BOOL hasCustomMessage;

@property(nonatomic, readwrite, strong, null_resettable) SystemMessage *systemMessage;
/** Test to see if @c systemMessage has been set. */
@property(nonatomic, readwrite) BOOL hasSystemMessage;

@property(nonatomic, readwrite, strong, null_resettable) RecallMessage *recallMessage;
/** Test to see if @c recallMessage has been set. */
@property(nonatomic, readwrite) BOOL hasRecallMessage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extra;

@property(nonatomic, readwrite) BOOL notifyPassThrough;

@property(nonatomic, readwrite, strong, null_resettable) RemindMessage *remindMessage;
/** Test to see if @c remindMessage has been set. */
@property(nonatomic, readwrite) BOOL hasRemindMessage;

@property(nonatomic, readwrite) int32_t requestEvent;

@end

/**
 * Fetches the raw value of a @c MessageBody's @c messageType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t MessageBody_MessageType_RawValue(MessageBody *message);
/**
 * Sets the raw value of an @c MessageBody's @c messageType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetMessageBody_MessageType_RawValue(MessageBody *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
