// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/taikang/im/protobuf/ProtocolType.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ProtocolType

typedef GPB_ENUM(ProtocolType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ProtocolType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ProtocolType_ComUnknown = 0,
  ProtocolType_ComChatMessageReq = 1,
  ProtocolType_ComChatMessageReqAck = 2,
  ProtocolType_ComChatMessageNotify = 3,
  ProtocolType_ComGroupMessageNotify = 4,
  ProtocolType_ComGroupMessageNotifyAck = 5,
  ProtocolType_ComGroupMessageReq = 6,
  ProtocolType_ComGroupMessageReqAck = 7,
  ProtocolType_ComHeartbeatReq = 8,
  ProtocolType_ComHeartbeatReqAck = 9,
  ProtocolType_ComConnectReq = 10,
  ProtocolType_ComConnectReqAck = 11,
  ProtocolType_ComDisconnectReq = 12,
  ProtocolType_ComDisconnectNotify = 13,
  ProtocolType_ComSystemMessageNotify = 14,
  ProtocolType_ComChatMessageNotifyAck = 15,
  ProtocolType_ComCustomerMessageReq = 16,
  ProtocolType_ComCustomerMessageReqNotify = 17,
  ProtocolType_ComCustomerMessageReply = 18,
  ProtocolType_ComCustomerMessageReplyNotify = 19,
  ProtocolType_ComReceiveStateMessageReq = 20,
  ProtocolType_ComReceiveStateMessageNotify = 21,
  ProtocolType_ComSessionStateMessageReq = 22,
  ProtocolType_ComSessionStateMessageNotify = 23,
  ProtocolType_ComBroadcastMessage = 24,
};

GPBEnumDescriptor *ProtocolType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ProtocolType_IsValidValue(int32_t value);

#pragma mark - ProtocolTypeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ProtocolTypeRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
