// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/taikang/im/protobuf/ReceiveStateMessageReq.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#import <SakuraKit/ReceiveStateMessageReq.pbobjc.h>

#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#import "ReceiveStateMessageReq.pbobjc.h"

#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ReceiveStateMessageReqRoot

@implementation ReceiveStateMessageReqRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - ReceiveStateMessageReqRoot_FileDescriptor

static GPBFileDescriptor *ReceiveStateMessageReqRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - ReceiveStateMessageReq

@implementation ReceiveStateMessageReq

@dynamic messageId;
@dynamic sessionId;
@dynamic sessionType;
@dynamic from;
@dynamic to;
@dynamic deviceType;
@dynamic domain;
@dynamic eventType;
@dynamic eventTargetId;

typedef struct ReceiveStateMessageReq__storage_ {
  uint32_t _has_storage_[1];
  int32_t deviceType;
  int32_t eventType;
  NSString *messageId;
  NSString *sessionId;
  NSString *sessionType;
  NSString *from;
  NSString *to;
  NSString *domain;
  NSString *eventTargetId;
} ReceiveStateMessageReq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "messageId",
        .dataTypeSpecific.className = NULL,
        .number = ReceiveStateMessageReq_FieldNumber_MessageId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ReceiveStateMessageReq__storage_, messageId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sessionId",
        .dataTypeSpecific.className = NULL,
        .number = ReceiveStateMessageReq_FieldNumber_SessionId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ReceiveStateMessageReq__storage_, sessionId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sessionType",
        .dataTypeSpecific.className = NULL,
        .number = ReceiveStateMessageReq_FieldNumber_SessionType,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ReceiveStateMessageReq__storage_, sessionType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "from",
        .dataTypeSpecific.className = NULL,
        .number = ReceiveStateMessageReq_FieldNumber_From,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ReceiveStateMessageReq__storage_, from),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "to",
        .dataTypeSpecific.className = NULL,
        .number = ReceiveStateMessageReq_FieldNumber_To,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(ReceiveStateMessageReq__storage_, to),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceType",
        .dataTypeSpecific.className = NULL,
        .number = ReceiveStateMessageReq_FieldNumber_DeviceType,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(ReceiveStateMessageReq__storage_, deviceType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "domain",
        .dataTypeSpecific.className = NULL,
        .number = ReceiveStateMessageReq_FieldNumber_Domain,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(ReceiveStateMessageReq__storage_, domain),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "eventType",
        .dataTypeSpecific.className = NULL,
        .number = ReceiveStateMessageReq_FieldNumber_EventType,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(ReceiveStateMessageReq__storage_, eventType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "eventTargetId",
        .dataTypeSpecific.className = NULL,
        .number = ReceiveStateMessageReq_FieldNumber_EventTargetId,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(ReceiveStateMessageReq__storage_, eventTargetId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ReceiveStateMessageReq class]
                                     rootClass:[ReceiveStateMessageReqRoot class]
                                          file:ReceiveStateMessageReqRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ReceiveStateMessageReq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\006\001\t\000\002\t\000\003\013\000\006\n\000\010\t\000\t\r\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
