// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/taikang/im/protobuf/SessionStateMessageNotify.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#import <SakuraKit/SessionStateMessageNotify.pbobjc.h>

#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#import "SessionStateMessageNotify.pbobjc.h"

#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - SessionStateMessageNotifyRoot

@implementation SessionStateMessageNotifyRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - SessionStateMessageNotifyRoot_FileDescriptor

static GPBFileDescriptor *SessionStateMessageNotifyRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - SessionStateMessageNotify

@implementation SessionStateMessageNotify

@dynamic messageId;
@dynamic sessionId;
@dynamic sessionType;
@dynamic from;
@dynamic to;
@dynamic deviceType;
@dynamic domain;
@dynamic state;
@dynamic extra;

typedef struct SessionStateMessageNotify__storage_ {
  uint32_t _has_storage_[1];
  int32_t deviceType;
  int32_t state;
  NSString *messageId;
  NSString *sessionId;
  NSString *sessionType;
  NSString *from;
  NSString *to;
  NSString *domain;
  NSString *extra;
} SessionStateMessageNotify__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "messageId",
        .dataTypeSpecific.className = NULL,
        .number = SessionStateMessageNotify_FieldNumber_MessageId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(SessionStateMessageNotify__storage_, messageId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sessionId",
        .dataTypeSpecific.className = NULL,
        .number = SessionStateMessageNotify_FieldNumber_SessionId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(SessionStateMessageNotify__storage_, sessionId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sessionType",
        .dataTypeSpecific.className = NULL,
        .number = SessionStateMessageNotify_FieldNumber_SessionType,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(SessionStateMessageNotify__storage_, sessionType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "from",
        .dataTypeSpecific.className = NULL,
        .number = SessionStateMessageNotify_FieldNumber_From,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(SessionStateMessageNotify__storage_, from),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "to",
        .dataTypeSpecific.className = NULL,
        .number = SessionStateMessageNotify_FieldNumber_To,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(SessionStateMessageNotify__storage_, to),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceType",
        .dataTypeSpecific.className = NULL,
        .number = SessionStateMessageNotify_FieldNumber_DeviceType,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(SessionStateMessageNotify__storage_, deviceType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "domain",
        .dataTypeSpecific.className = NULL,
        .number = SessionStateMessageNotify_FieldNumber_Domain,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(SessionStateMessageNotify__storage_, domain),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "state",
        .dataTypeSpecific.className = NULL,
        .number = SessionStateMessageNotify_FieldNumber_State,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(SessionStateMessageNotify__storage_, state),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "extra",
        .dataTypeSpecific.className = NULL,
        .number = SessionStateMessageNotify_FieldNumber_Extra,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(SessionStateMessageNotify__storage_, extra),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SessionStateMessageNotify class]
                                     rootClass:[SessionStateMessageNotifyRoot class]
                                          file:SessionStateMessageNotifyRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(SessionStateMessageNotify__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\001\t\000\002\t\000\003\013\000\006\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
