// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/taikang/im/protobuf/message/ShortVideoMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ShortVideoMessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ShortVideoMessageRoot : GPBRootObject
@end

#pragma mark - ShortVideoMessage

typedef GPB_ENUM(ShortVideoMessage_FieldNumber) {
  ShortVideoMessage_FieldNumber_MediaId = 1,
  ShortVideoMessage_FieldNumber_ThumbMediaId = 2,
  ShortVideoMessage_FieldNumber_Duration = 3,
  ShortVideoMessage_FieldNumber_Size = 4,
  ShortVideoMessage_FieldNumber_Height = 5,
  ShortVideoMessage_FieldNumber_Width = 6,
};

@interface ShortVideoMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *mediaId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbMediaId;

@property(nonatomic, readwrite) int32_t duration;

@property(nonatomic, readwrite) int64_t size;

@property(nonatomic, readwrite) int32_t height;

@property(nonatomic, readwrite) int32_t width;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
