// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/taikang/im/protobuf/message/ShortVideoMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#import <SakuraKit/ShortVideoMessage.pbobjc.h>

#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#import "ShortVideoMessage.pbobjc.h"

#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ShortVideoMessageRoot

@implementation ShortVideoMessageRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - ShortVideoMessageRoot_FileDescriptor

static GPBFileDescriptor *ShortVideoMessageRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - ShortVideoMessage

@implementation ShortVideoMessage

@dynamic mediaId;
@dynamic thumbMediaId;
@dynamic duration;
@dynamic size;
@dynamic height;
@dynamic width;

typedef struct ShortVideoMessage__storage_ {
  uint32_t _has_storage_[1];
  int32_t duration;
  int32_t height;
  int32_t width;
  NSString *mediaId;
  NSString *thumbMediaId;
  int64_t size;
} ShortVideoMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "mediaId",
        .dataTypeSpecific.className = NULL,
        .number = ShortVideoMessage_FieldNumber_MediaId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ShortVideoMessage__storage_, mediaId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "thumbMediaId",
        .dataTypeSpecific.className = NULL,
        .number = ShortVideoMessage_FieldNumber_ThumbMediaId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ShortVideoMessage__storage_, thumbMediaId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "duration",
        .dataTypeSpecific.className = NULL,
        .number = ShortVideoMessage_FieldNumber_Duration,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ShortVideoMessage__storage_, duration),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "size",
        .dataTypeSpecific.className = NULL,
        .number = ShortVideoMessage_FieldNumber_Size,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ShortVideoMessage__storage_, size),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "height",
        .dataTypeSpecific.className = NULL,
        .number = ShortVideoMessage_FieldNumber_Height,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(ShortVideoMessage__storage_, height),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "width",
        .dataTypeSpecific.className = NULL,
        .number = ShortVideoMessage_FieldNumber_Width,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(ShortVideoMessage__storage_, width),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ShortVideoMessage class]
                                     rootClass:[ShortVideoMessageRoot class]
                                          file:ShortVideoMessageRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ShortVideoMessage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\007\000\002\014\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
