// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/taikang/im/protobuf/SystemMessageNotify.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#import <SakuraKit/SystemMessageNotify.pbobjc.h>
#import <SakuraKit/MessageBody.pbobjc.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#import "SystemMessageNotify.pbobjc.h"
#import "MessageBody.pbobjc.h"
#endif


// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - SystemMessageNotifyRoot

@implementation SystemMessageNotifyRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - SystemMessageNotifyRoot_FileDescriptor

static GPBFileDescriptor *SystemMessageNotifyRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - SystemMessageNotify

@implementation SystemMessageNotify

@dynamic messageId;
@dynamic sessionId;
@dynamic to;
@dynamic deviceType;
@dynamic hasBody, body;
@dynamic domain;
@dynamic sessionLabel;
@dynamic sessionType;

typedef struct SystemMessageNotify__storage_ {
  uint32_t _has_storage_[1];
  int32_t deviceType;
  NSString *messageId;
  NSString *sessionId;
  NSString *to;
  MessageBody *body;
  NSString *domain;
  NSString *sessionLabel;
  NSString *sessionType;
} SystemMessageNotify__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "messageId",
        .dataTypeSpecific.className = NULL,
        .number = SystemMessageNotify_FieldNumber_MessageId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(SystemMessageNotify__storage_, messageId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sessionId",
        .dataTypeSpecific.className = NULL,
        .number = SystemMessageNotify_FieldNumber_SessionId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(SystemMessageNotify__storage_, sessionId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "to",
        .dataTypeSpecific.className = NULL,
        .number = SystemMessageNotify_FieldNumber_To,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(SystemMessageNotify__storage_, to),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceType",
        .dataTypeSpecific.className = NULL,
        .number = SystemMessageNotify_FieldNumber_DeviceType,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(SystemMessageNotify__storage_, deviceType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "body",
        .dataTypeSpecific.className = GPBStringifySymbol(MessageBody),
        .number = SystemMessageNotify_FieldNumber_Body,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(SystemMessageNotify__storage_, body),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "domain",
        .dataTypeSpecific.className = NULL,
        .number = SystemMessageNotify_FieldNumber_Domain,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(SystemMessageNotify__storage_, domain),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sessionLabel",
        .dataTypeSpecific.className = NULL,
        .number = SystemMessageNotify_FieldNumber_SessionLabel,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(SystemMessageNotify__storage_, sessionLabel),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sessionType",
        .dataTypeSpecific.className = NULL,
        .number = SystemMessageNotify_FieldNumber_SessionType,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(SystemMessageNotify__storage_, sessionType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SystemMessageNotify class]
                                     rootClass:[SystemMessageNotifyRoot class]
                                          file:SystemMessageNotifyRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(SystemMessageNotify__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\005\001\t\000\002\t\000\004\n\000\007\014\000\010\013\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
